---
- name: create volume-dirs
  file:
    path: "/volumes/activemq/{{item}}"
    state: directory
  with_items:
  - config
  - lib

- name: copy conf to host
  template:
    src: "{{item}}.j2"
    dest: "/volumes/activemq/config/{{item}}"
  with_items:
  - activemq.xml
  - log4j.properties
  - jmx.password

- name: copy activemq-plugin
  copy:
    src: "../kalinka-activemq-plugin/target/kalinka-activemq-plugin-{{activemq_plugin_version}}.jar"
    dest: /volumes/activemq/lib/kalinka-activemq-plugin.jar

- name: start container
  docker_container:
    name: activemq
    image: "rmohr/activemq:{{activemq_version}}" 
    docker_host: "{{docker_host}}"
    network_mode: host
    state: "{{activemq_state}}"
    recreate: "{{activemq_reset or reset_all}}"
    restart: "{{activemq_restart}}"
    restart_policy: unless-stopped
    volumes:
    - /volumes/activemq/config/log4j.properties:/opt/activemq/conf/log4j.properties
    - /volumes/activemq/config/activemq.xml:/opt/activemq/conf/activemq.xml
    - /volumes/activemq/config/jmx.password:/opt/activemq/conf/jmx.password
    - /volumes/activemq/lib/kalinka-activemq-plugin.jar:/opt/activemq/lib/kalinka-activemq-plugin.jar

