---
- name: "wait for zookeeper-cluster coming up (TODO: Replace this with active availability-check)"
  pause:
    seconds: 10

- name: create chroots
  znode:
    hosts: "{{zk_hosts}}"
    name: "{{item}}"
    state: present
  with_items:
  - "{{zk_chroots['activemq']}}"
  - "{{zk_chroots['kafka']}}"
  when: (zookeeper_reset or reset_all) and ansible_hostname == hostvars[groups['zookeeper'][0]]['ansible_hostname']
