---
- name: "wait for zookeeper-cluster coming up (TODO: Replace this with active availability-check)"
  pause:
    seconds: 10

- name: create chroots
  znode:
    hosts: "{% for host in groups['zookeeper'] %}{{hostvars[host]['inventory_hostname']}}:{{zk_client_port}}{% if not loop.last %},{% endif %}{% endfor %}"
    name: "{{item}}"
    state: present
  with_items:
  - "{{zk_chroots['activemq']}}"
  - "{{zk_chroots['kafka']}}"
  when: (zookeeper_reset or reset_all) and ansible_hostname == hostvars[groups['zookeeper'][0]]['ansible_hostname']
